baseURL = 'https://kaarnam.com/'
languageCode = 'en-us'
title = 'Karthika Namboothiri'
theme = 'maverick'

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^GITHUB_PAGES$']

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "All published work"
    url = "/posts/"
    weight = -200
